enum REAL_ESTATE_LISTING_ERROR_CODES {
    CANNOT_CREATE_ID = "CANNOT_CREATE_ID",
    CANNOT_CREATE_TYPE = "CANNOT_CREATE_TYPE",
    CANNOT_CREATE_PRICE = "CANNOT_CREATE_PRICE",
    CANNOT_CREATE_ADDRESS = "CANNOT_CREATE_ADDRESS",
}

export default REAL_ESTATE_LISTING_ERROR_CODES;
